### PR TITLE
Added the error pop up

### PR DESCRIPTION
**Pull request by g-kabra**
Added the error pop up and gave it a minimal design. Closing the notification reloads the screen so that it's not stuck on the loading screen, or shows previous results.

Error type 1: 
image

Error type 2:
image

Also shows a connectivity issue if the recipe is unable to load, but doesn't refresh screen then.

solves #1 

https://user-images.githubusercontent.com/57868024/157908871-3a017b86-8509-412f-a249-e48793a7a22c.mp4

https://user-images.githubusercontent.com/57868024/157908876-1da0bcd2-ea98-4192-8706-b02d77deb035.mp4

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 The error messages and UI look fine, but there is no need (I feel) for reloading the page. When there is no reloading, does the pre-existing functionality seem enough or not? Try the X button on the modal, for instance.

**Comment by g-kabra** [comment]
Yes, we can use the X button, and also remove the loading screen definitely. I've implemented that in case ingredients fail to load, same thing can be done here. It was my first thought so I put it in and then didn't change it😅

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 Got it, but since the close modal button already has an event listener for click that works as intended, remove the new ones. 

When contributing to repositories to add a new feature (like here), it is important to try to first understand and then utilise the pre-existing code if possible instead of doing a similar thing in a different style. Basically you need to make sure your change seamlessly integrates into the original codebase and doesn't stick out too much as having a different style. Follow any code conventions that you observe. Like here, a way for closing modals is already set, so you don't need to re-invent the wheel. 

This is something you'll slowly get a feel for through more experience with Open Source :)

**Comment by g-kabra** [comment]
Okay ma'am, will do. Give me a minute :)

**Comment by g-kabra** [comment]
Done :)

**Comment by N-Shar-ma** [comment]
@AlphaGaurav7 Another little thing to keep in mind: leaving out commented lines of code in a PR, which were only there for testing / debugging purposes is not good, as it just clutters the codebase. Remove them the next time!

**Pull request closed without merging**
