### PR TITLE
added footer and credits

### PR DESCRIPTION
**Pull request by axshatj**
solved issue #3 
Screenshot 2022-03-13 151508

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@axshatj Nice and simple! 

Can you test if the footer does not cover up content when there is enough content to need to scroll down? For example, when you search for "Indian" dishes, do all the images in the bottom row show up fully and aren't covered by footer? If you provide a screenshot showing that the footer doesn't hide any content, I'll accept this!

**Comment by axshatj** [comment]
@N-Shar-ma ma,am , here it looks like this
Screenshot 2022-03-13 153012

**Comment by N-Shar-ma** [comment]
@axshatj Could you show mobile view as well?

**Comment by axshatj** [comment]
yes ma'am in mobile mode footer is coming in between images...
I'll try to fix it

**Comment by axshatj** [comment]
here it looks like this @N-Shar-ma ma'am
Screenshot 2022-03-13 163709

**Comment by N-Shar-ma** [comment]
@axshatj That looks fine, did you fix the code? If yes, commit and push those changes too

**Comment by axshatj** [comment]
yes ma'am i edited the code shall i PR?

**Comment by N-Shar-ma** [comment]
@axshatj The PR auto updates whenever you commit and push any new code, so this is now ready! Accepted :)

**Comment by axshatj** [comment]
oh nice, thank u ma'am

**Pull request closed without merging**
