### PR TITLE
Fixed #2

### LINKED ISSUE #2: Remove the mysterious extra space after ingredients
For dishes with less ingredients, there is a lot of extra space visible before the instructions. The amount of this space seems to be inversely proportional to the number of ingredients. Investigate what is causing so many blank lines and fix the UI so that there are no unpredictable blank lines after the list of ingredients.

Hint: Investigate the data being returned by the API

Attach 2 screenshots, one for before and for after, showing how you have fixed this UI bug. Feel free to elaborate in writing how you figured out what exactly was wrong, since finding the root cause of a bug is as important as fixing it.

Visual changes are much easier for PR reviewers when the contributor adds screenshots / gifs, as appropriate, which show the change at a cursory glance, so make this a habit!

### PR DESCRIPTION
**Pull request by KarthikS373**
Solved : #2 
Removes the mysterious extra space after ingredients
After :
after
 Before:
before

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@KarthikS373 There are too many unnecessary changes, mostly formatting ones (please disable your linter/ formatter! You should stick to the code style conventions of the codebase you're contributing to and not enforce any style on it)

Also remove the changes relating to the credits footer

**Comment by KarthikS373** [comment]
@N-Shar-ma Ma'am cleared all lints and formatting and have commited to the existing PR can you please check and confirm

**Comment by N-Shar-ma** [comment]
@KarthikS373 Please also remove the footer related code since that is unrelated to issue #2. There still is a little linter formatting left but we'll let it slide this once

**Comment by N-Shar-ma** [comment]
@KarthikS373 Sorry time's up. I suggest you learn how to work with branches in git first, and make PRs using different branches, so you don't have unrelated commits in any PR.

**Pull request closed without merging**
