### PR TITLE
Fixed issue #3: Added footer to give credit to the api service

### PR DESCRIPTION
**Pull request by Ilikepizza2**
Fixed issue #3: Added footer to give credit to the api service
Screenshots are attached below: 
1. On desktop 
Screenshot_20220313_184211
2. On mobile
WhatsApp Image 2022-03-13 at 18 50 18

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Liked the use of the API's branding! Only critique is that it looks a little too distracting and take up a little too much space, but overall nice work. Maybe having everything in one line, and removing the plain link, and only using the image link would be better. If you really want, you can implement these suggestions, or just try to make the footer a little more subtle for 1 more bonus point, but it's fine as is too!

**Comment by Ilikepizza2** [comment]
Sure! Thanks for the suggestion. I have updated the footer according to your suggestions and lowered the saturation of footer to make it a bit subtle. Screenshot is attached below:
Screenshot_20220313_191710

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Can you also make the logo a little smaller so the text size isn't so much bigger than the plain text?

**Comment by Ilikepizza2** [comment]
Didn't think about that 🤔
Please wait a minute I'll try it.

**Comment by Ilikepizza2** [comment]
Does it seem alright now?
Screenshot_20220313_192957

**Comment by N-Shar-ma** [comment]
@Ilikepizza2 Much better! Maybe make the text's color match the orange of the logo as well? 

I know these are a lot of little changes but it needs to be really pretty for +2 :)

**Comment by Ilikepizza2** [comment]
Hehe alright XD

**Comment by Ilikepizza2** [comment]
Is it ok now? Added border and shadow for consistency and better visibility.
Screenshot_20220313_1945391

**Pull request closed without merging**
