### PR TITLE
Solves 🎯 #2

### PR DESCRIPTION
**Pull request by superiorsd10**
**EXACT PROBLEM**

Actually, the for loop iterating through the meal was looping 20 times whether the measurements and ingredients are empty or not. So it was adding some extra spaces after the ingredients. 

**SOLUTION**

On line 62 in the for loop, I inserted an if condition, in which if both the measure and ingredients are empty, then it will not add insert any extra space. 

Here are the results:

_Before:_

Screenshot_17

_After:_

Screenshot_18

### CODE REVIEW

**Comment by N-Shar-ma** [comment]
@superiorsd10 Nice work, but you seem to have solved 2 issues in 1 PR. Please remove the changes unrelated to solving issue #2. Also reminder to mention the issue being solved in the PR description, not title, since GitHub automatically detects issues mentioned in the PR message body, but not in title. Another suggestion: no need to specify line numbers for the changes. They only confuse the reader and are unnecessary.

**Comment by superiorsd10** [comment]
No, @N-Shar-ma Ma'am. Actually, I had created the pull request for issue #2 but as I have also worked on issue #3 in this repo, it's showing my previous commit as well. I have just solved only one issue in this PR.

Thank You, I'll be editing my title.

**Comment by N-Shar-ma** [comment]
@superiorsd10 You are supposed to make different branches for each PR you make, that way you'll only have the relevant commits in each PR. In case you have a problem with understanding how to work with branches, try working on the git repository first.

Also you did not not need to edit the title but the description. Description is the part where you have written all the details regarding your solution and attached the screenshots. You may look at other accepted PRs for reference, which mention the issue number in the description, NOT title.

**Comment by superiorsd10** [comment]
@N-Shar-ma Ma'am so should I close this pull request and make another one with a new branch this time?

**Comment by N-Shar-ma** [comment]
> @N-Shar-ma Ma'am so should I close this pull request and make another one with a new branch this time?

Yes that's exactly what you have to do :) I'll close this

**Pull request closed without merging**
